---
title: "09012022_delta_ung"
author: "Chandler Sutherland"
date: '2022-09-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

## Functions
Read in the excel file 
```{r}
df <- readxl::read_xlsx(path="C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E9\\Colony_count_excel\\09012022_HsAPOBEC2_PmCDA1_ung.xlsx")

#remove too many or too few colonies
#not doing now since hand wavey test anyway and would lose all rif data 
##add if statement to do it for me
TITC <- df %>% filter(count=='TITC') %>% count()
TNTC <- df %>% filter(count=='TNTC') %>% count()
paste(TITC$n, "plates removed for insufficient colonies to count, ", TNTC$n, "plates removed for too many colonies to count.")
df <- df %>% filter(count!='TITC' & count!='TNTC')
df$count <- as.numeric(df$count)
df$CFU <- as.numeric(df$CFU)
df
```
Average the technical replicates 
```{r}
#average tech reps, then calculate mut freq for each one
constructs_avg <- df %>% group_by(construct, plate, induction) %>% summarize(tech.mean=mean(CFU), 
                                                                             tech.n=n(), 
                                                                             tech.sd=sd(CFU))

#calculate mutation frequency 
lb_cam_kan <- constructs_avg[which(constructs_avg$plate == 'LB_CAM_KAN'),]$tech.mean
lb_rif_cam_kan <- constructs_avg[which(constructs_avg$plate == 'LB_RIF_CAM_KAN'),]$tech.mean
mut_freq = lb_rif_cam_kan/lb_cam_kan
constructs_mut <- constructs_avg %>% group_by(construct, induction) %>% summarize(n=n())
constructs_mut$mut_freq <- mut_freq
```


```{r}
#This forces uninduced before induced
constructs_mut$induction <- factor(constructs_mut$induction, levels = c('uninduced', 'induced'), ordered=TRUE)
#R2_p_mut$induction <- factor(R2_p_mut$induction, levels = c('uninduced', 'induced'), ordered=TRUE)
ggplot(constructs_mut,
       aes(x=induction, y=mut_freq, fill=induction))+
  geom_boxplot()+
  facet_wrap(~construct)+
  scale_y_log10()+
  labs(x = 'induction', y='mutation frequency', title="ecoli delta ung")
```


Copy in from 7.16 to plot both biological reps 


## Functions
Read in the excel file 
```{r}
rep_0716 <- readxl::read_xlsx(path="C:\\Users\\chand\\Box Sync\\Krasileva_Lab\\Research\\chandler\\Krasileva Lab\\E9\\e9\\07162022_summary_table.xlsx")

rep_0716 <- rep_0716 %>% filter(construct != 'HsAID') %>% mutate(date='07162022')
constructs_mut <- constructs_mut %>% mutate(date='09012022')

reps <- rbind(rep_0716, constructs_mut)
```

```{r}
#This forces uninduced before induced
reps$induction <- factor(reps$induction, levels = c('uninduced', 'induced'), ordered=TRUE)
#R2_p_mut$induction <- factor(R2_p_mut$induction, levels = c('uninduced', 'induced'), ordered=TRUE)
ggplot(reps,
       aes(x=induction, y=mut_freq, fill=induction))+
  geom_boxplot()+
  facet_wrap(~construct)+
  geom_jitter()+
  scale_y_log10()+
  labs(x = 'induction', y='mutation frequency', title="ecoli delta ung")
```
```{r}
ggplot(reps,
       aes(x=construct, y=mut_freq, fill=induction))+
  geom_boxplot()+
  geom_point(position=position_jitterdodge())+
  scale_y_log10()+
   theme(text = element_text(size = 20))+   
  labs(y='Mutation frequency (log10 Rif resistant cfu -1)', x='')
```
```{r}
reps %>% group_by(construct, induction) %>% summarize(bio.mean=mean(mut_freq), 
                                                                             bio.n=n(), 
                                                                             bio.sd=sd(mut_freq))
```

There's a lot of deviation in PmCDA1 induced, which I think is messing with the t test. 
```{r}

HsAPOBEC_t <- t.test(mut_freq ~ induction, data=reps %>% filter(construct == 'HsAPOBEC2'))$p.value
PmCDA1_t <- t.test(mut_freq ~ induction, data=reps %>% filter(construct == 'PmCDA1'))$p.value
print(paste("The p value for HsAPOBEC 2 is:", HsAPOBEC_t, "The p value for PmCDA1 is ", PmCDA1_t))
```

